# Chaper 2

## Problem 1

In [11]:
my_list=[1,3,5,7,9]
def stats(L):
    return max(L),min(L), (sum(L)/len(L))

In [9]:
stats(my_list)

(9, 1, 5.0)

## Problem 2

In [26]:
#Problem 2
myint = 7
mystr = "seven"
mylist = [1, 2, 3]
mytuple = ('apple', 'orange','pear')
myset = {1, 2, 3}

In [27]:
myint_=myint
mystr_=mystr
mylist_=mylist
mytuple_=mytuple
myset_=myset

In [28]:
myint = 8
mystr = "eight"
mylist[2] = 3
mytuple += (1,)
myset.add(4)

In [29]:
myint == myint_
#int is immutable

False

In [30]:
mystr == mystr_
#str is immutable

False

In [31]:
mylist == mylist_
#list is mutable

True

In [32]:
mytuple == mytuple_
#tuple is immutable

False

In [33]:
myset == myset_
#set is mutable

True

## Problem 3

In [58]:
import calculator

In [62]:
def hypotenuse(a, b):
    length = sqrt(add(a,b)*add(a,b)-2*product(a,b))
    return length

In [63]:
hypotenuse(3, 4)

5.0

# Chapter 3

## Problem 1

In [41]:
class Backpack:
    """A Backpack object class. Has a name, color, size cap, and a list of contents.
    
    Attributes:
        name (str): name of owner
        color(str): name of the color
        max_size (int): max number of items that can fit the jetpack
        contents (list): the contents of the jetpack
    """
    def __init__(self, name, color, max_size=5):
        """set the name, color, size cap, and initialize an empty list
        of contents
        """
        self.name=name
        self.color=color
        self.max_size=max_size
        self.contents=[]
    def put(self, item):
        """add item to the backpack's list of contents if the 
        number of contents is smaller than the size cap; otherwise,
        report no room"""
        if len(self.contents) < self.max_size:
            self.contents.append(item)
        else:
            print("No Room!")
    def take(self, item):
        """take item to the backpack's list of contents"""
        self.contents.remove(item)
    def dump(self):
        """empty the list of contents"""
        self.contents=[]

In [80]:
my_backpack=Backpack("Ruby","red")

In [69]:
type(my_backpack)

__main__.Backpack

In [81]:
print(my_backpack.name, my_backpack.color, my_backpack.max_size)

Ruby red 5


In [101]:
def test_backpack():
    testpack=Backpack("Barry","black")
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")
    for item in ['pencil','pen','paper','computer']:
        testpack.put(item)
    print('Contents:', testpack.contents)

In [102]:
test_backpack()

Contents: ['pencil', 'pen', 'paper', 'computer']


## Problem 2

In [70]:
class Jetpack(Backpack):
    """A jetpack object class. Inherits from the backpack class.
    A jetpack is smaller than a backpack and can be used to fly.
    
    Attributes:
        name (str): name of owner
        color(str): name of the color
        max_size (int): max number of items that can fit the jetpack
        contents (list): the contents of the jetpack
        fuel (int): the amount of fuel that the jetpack contains
    """
    def __init__(self, name, color, max_size=2, fuel=10):
        """Use the Backpack constructor to initialize the name, color, max_size.
        Override the constructor so that it also initialize the fuel attribute.
        By default, the jetpack can only hold 2 items and 10 units of fuel.
        """
        self.fuel=fuel
        Backpack.__init__(self, name, color, max_size)
    def fly(self, item):
        """define a new method fly by decrementing the amount of fuel
        by the amount used in fly. Or print out "Not enough fuel" if the
        used amount is larger than the original fuel cap
        """
        if item <= self.fuel:
            self.fuel=self.fuel-item
        else:
            print('Not enough fuel!')
    def dump(self):
        """override the dump method fly so that both the contents and the
        fuel cap are emptied
        """
        self.contents=[]
        self.fuel=[]

In [75]:
my_backpack2=Jetpack("Ruby","red")
print(my_backpack2.max_size)
my_backpack2.fly(9)
print(my_backpack2.fuel)
my_backpack2.dump()
print(my_backpack2.contents)

2
1
[]


# Chapter 4

## Problem 1

In [2]:
import numpy as np

In [103]:
def ma_product(a, b, c, d, e):
    A = np.array([a,b])
    B = np.array([c,d,e])
    return np.dot(A, B)

In [104]:
a = [3, -1, 4]
b = [1, 5, -9]
c = [2, 6, -5, 3]
d = [5, -8, 9, 7]
e = [9, -3, -2, -3]

In [105]:
ma_product(a, b, c, d, e)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2

In [112]:
def cal_ma(x, y, z):
    A = np.array([x, y, z])
    return -np.dot(np.dot(A, A),A)+9*np.dot(A,A)-15*A

In [113]:
x = [3, 1, 4]
y = [1, 5, 9]
z = [-5, 3, 1]

In [114]:
cal_ma(x,y,z)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Problem 5

In [29]:
def make_matrix(f, g, h):
    global A
    A = np.arange(f).reshape((3, 2)).T
    global B
    B = np.tril(np.full_like(np.eye(3), g))
    global C
    C = h * np.eye(3)
    return A, B, C 
  
f = 6
g = 3
h = -2

make_matrix(f, g, h)

(array([[0, 2, 4],
        [1, 3, 5]]),
 array([[3., 0., 0.],
        [3., 3., 0.],
        [3., 3., 3.]]),
 array([[-2., -0., -0.],
        [-0., -2., -0.],
        [-0., -0., -2.]]))

In [38]:
def stacking(A, B, C):
    make_matrix(f, g, h)
    first_col = np.vstack((np.zeros((2,3)), A, B))
    second_col = np.vstack((A.T, np.zeros((2,2)), np.zeros((2,2))))
    third_col = np.vstack((np.eye(3), np.zeros((1, 3)), C))
    return np.hstack((first_col, second_col, third_col))

In [39]:
stacking (A, B, C)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  2.,  4.,  4.,  5.,  0.,  0.,  1.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])